### PR TITLE
chore(build): update deasync to 0.1.12 for fix process._tickDomainCal…

### PR DESCRIPTION
**Pull request by rafaelhdr**
Possible fix for [issue 8](https://github.com/pact-foundation/karma-pact/issues/8).

### CODE REVIEW

**Comment by mboudreau** [comment]
@rafaelhdr thanks for the PR.  I don't know how I've missed this in the past, but as a general rule, most Pact project dependencies are restricted to only a single version that we know works.  Could I please ask you to remove all `~` and `^` from the package.json so that we don't have this issue again the future if one of our dependencies update something that break?

Thanks.

**Comment by rafaelhdr** [comment]
Sure. So, I will remove `~` and `^` from all packages (not only deasync), OK?

**Comment by mefellows** [comment]
👍

**Comment by mboudreau** [comment]
Yep :)

**Comment by rafaelhdr** [comment]
Done :)

**Comment by mefellows** [comment]
Thanks @rafaelhdr, will get a release out shortly.

**Pull request merged**
