### PR TITLE
Fix multiple pact with promise and deasync

### PR DESCRIPTION
**Pull request by mcjc29**
A not very pretty, quick fix to @pact-foundation/karma-pact/issues/15

### CODE REVIEW

**Comment by mboudreau** [comment]
@mcjc29 thank you for this PR, very appreciated.

I was thinking, is it possible to keep an array of all promises (the output of `pacts.map`), then use deasync to iterate through them (with reduce) to see if they're all done?

If you can, that might be a more readable solution. Cheers.

**Comment by Mardzy** [comment]
@mboudreau we sat and had a long think about how we wanted to try to accomplish what you've asked, but wondered if this solution may work for all parties involved.

Looking forward to your feedback. Cheers.

**Comment by Mardzy** [comment]
Hello @mboudreau @mcjc29 
After using the code for the karma-pact v2.1.6, it has fixed our issue and allows our code to run without issue.
The problem is that this version has yet to be released to the npm registry.
Is there a chance someone can publish v2.1.6?
Best regards,
Paul

**Comment by mboudreau** [comment]
@Mardzy Sorry, I think something went wrong with 2.1.6 release and was fixed with a bumped version of 2.1.8.  Try that one please.

**Comment by mefellows** [comment]
Yep, our npm key was recycled due to that point security beach a few months ago

**Pull request closed without merging**
