### PR TITLE
Add support for NodeJS > 12.10

### LINKED ISSUE #20: Pact Mock Server startup hanging since NodeJS v12.11
Hello,

I am facing the issue, that with the latest version of karma-pact and nodejs the process hangs right after starting the Pact Server. I get the success Logging information, but then nothing happens.

```
$ ng test --watch false
10% building 3/3 modules 0 active[2019-11-22T11:37:26.506Z]  INFO: pact-node@10.2.2/13260 on PCNAME:
    Creating Pact Server with options:
    {"cors":true,"port":9570,"consumer":"ui","provider":"service","dir":"Z:\\schurz\\ui\\pacts","pactFileWriteMode":"overwrite","ssl":false,"host":"localhost"}
10% building 6/6 modules 0 active22 11 2019 12:37:30.042:INFO [pact]: Pact Mock Server running on port: 9570
```

The last nodejs it works with is v12.10 . Not really knowing what I do, I had a closer noob look at the Promise, since I read, that nodejs changed some fundamental stuff to boost performance for await and all functionality of promises.
When I go into the index.js file and change the following:
```
var promise = Promise || require("bluebird");
to
var promise = require("bluebird");
```
it all works fine again.

Do you know why it behaves like this? What changed in nodejs 12.10 to 12.11 according to promises to have this impact?

Best, Jonas

### PR DESCRIPTION
**Pull request by michelefenu**
This PR aims to add support for NodeJS versions greater than 12.10 that are currently affected by the related issue.

I managed to make it work by removing `promise.all` and falling back on a simpler implementation.

Closes #20

### CODE REVIEW

**Comment by michelefenu** [comment]
* the Travis build fails on Node 6 (linux), probably due to a build job configuration
travis-build

**Comment by mefellows** [comment]
Thanks so much for this. I'll take a look today.

I think we can drop support for Node 6 now as it's EOL

**Comment by mhp-borisbojic** [comment]
Any news on this? When can we expect a new release with node >12.x support? :)

**Comment by mefellows** [comment]
Release on its way - apologies for the delay!

**Comment by mhp-borisbojic** [comment]
Awesome! :)

**Pull request merged**
