### PR TITLE
add the ability to run multiple Pact Servers

### PR DESCRIPTION
**Pull request by BenDave**
Hi,

This is a fix for issue #1, which we've been using in our own organization.

I'll be happy to make any amendments suggested.

### CODE REVIEW

**Comment by mboudreau** [comment]
@BenDave Can you explain your situation more as to what you're trying to accomplish and how this fixes that?  I might have a different suggestion on how to enable what you're trying to get done depending on the situation.

**Comment by BenDave** [comment]
A good description for the problem that I am trying to solve is available here https://github.com/pact-foundation/pact-js/issues/59 - It is also mentioned in the README.me in my PR for reference. 
Hopefully that should clarify your understanding of the issue.
From what I understand this is also the issue that is described in https://github.com/pact-foundation/karma-pact/issues/1

**Comment by mboudreau** [comment]
@BenDave I'm not a fan of the convention of this PR.  In my mind, the better way of doing it would be to have the ability to either specify an object for a single pact configuration, or an array to have multiple.  For example, to have multiple pact servers, you'd do something along this:

```
module.exports = function (config) {
  config.set({
    // in here we are simply telling to use Jasmine with Pact
    frameworks: ['jasmine', 'pact'],
    // the Pact opts will go here
    pact: [
    	{
		  port: 1234,     
		  consumer: "consumer",
		  provider: "first-provider" 
		},
		{
		  port: 1235,     
		  consumer: "consumer",
		  provider: "second-provider" 
		}
    ]
  })
```

This way we can keep each config completely separate and allow more control for each of these servers depending on the situation.  Would this method work for your situation?

**Comment by BenDave** [comment]
@mboudreau that is an interesting suggestion, I have one query about it however:

Although the karma-pact configuration can specify a consumer and provider name, the consumer and provider names need to be specified by the consumer Pact Test anyway, otherwise an error is thrown:
> Error: You must provide a Consumer for this pact.

This means that specifying the consumer and provider names in the karma configuration is redundant since they are optional, while they are mandatory as part of the pact tests. (Which makes me wonder why they can be specified there in the first place), which brings us back to my original implementation.

It is interesting to note that if the karma-pact configuration and pact test specify a different consumer (or provider) name then 2 different pact files will be generated.

This situation is a bit obscure, I'm happy to proceed according to your suggestion though, I'll be waiting for your comments on this.

**Comment by mboudreau** [comment]
@BenDave Hm, if that's the case, that's actually an issue with [pact-js](https://github.com/pact-foundation/pact-js/blob/master/src/pact-web.js#L33).  I'm not sure why it's forcing it because it can in fact work without it and use the one specified on the server.  

I think this is a bigger issue that we need to discuss within the foundation about the interaction we should be promoting.  Personally, I prefer having pact-js specify when it starts, which consumer it is and what provider it's expecting and not when the pact service starts.  In the meantime though, are you willing/comfortable to do the PR for the new change I've mentioned? If not, I'll take it over.

@mefellows @bethesque @uglyog Any thoughts on this?

**Comment by BenDave** [comment]
@mboudreau I updated the code as suggested.

**Comment by bethesque** [comment]
In regards to the underlying mock service, you only need the consumer and provider names at the time the pact file is written at the very end, though you can provide them at start up time if you really want. I don't think I understand the interaction between the karma code and the pact-js code well enough to understand the implications of each proposal.

**Comment by mboudreau** [comment]
@bethesque In that case, I might just remove it as an option in pact-node and karma-pact as to keep with the standard of only specifying it at write time.

**Comment by bethesque** [comment]
It still makes sense to specify it in the same block of code where you set the port, because it should be done exactly once per mock service instance, and it makes sense to capture all that information together. But it's only actually used at the end.

**Comment by mboudreau** [comment]
@bethesque Alright then. In that case, that means we should have it as optional in pact-js.  @mefellows could you make this happen?

@BenDave Sorry for taking a while, I'll merge this tonight, do a few updates and release a new version.

Cheers.

**Comment by mefellows** [comment]
Sorry to be late to the party.

Agree, allowing the user to specify all options together makes sense. It's a bit confusing as we have multiple ways of using pact, depending on the context. This is probably a hangover of adding `karma` and browser based support post the initial pact implementation.

I'm going to update only `pact-web` to make `consumer` and `provider` optional, but not `pact` which is the usual front door, so to speak (`karma-pact` doesn't use the `pact` library directly). 

This could be a potentially dangerous change (without those details if there is a configuration issue you won't find out until all of the tests have successfully run and we try to finalise the pact), so i'm going to proceed with caution.

**Comment by mefellows** [comment]
I've just pushed https://github.com/pact-foundation/pact-js/pull/96 to resolve this. Feedback welcome.

If all successful, I'll bump version of pact js and release in the next few days.

**Comment by mboudreau** [comment]
@mefellows agreed.  I think we need to have a chat about the grander scheme of things in terms of interactions with pact across the board.

**Pull request merged**
